name: Device Software
on:
  push:
    paths:
      - 'src/device/**'
  pull_request:
    branches: [ develop, master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARTIFACTS_DIR: ${{github.workspace}}/og-artifacts
    steps:
    - name: Determine branch to build
      # Source branch of pull request or to which commit pushed
      run: |
        if [[ ${{ github.event_name }} == 'pull_request' ]]
        then
          BRANCH="${{github.head_ref}}"
        elif [[ ${{ github.event_name }} == 'push' ]]
        then
          BRANCH="${GITHUB_REF##*/}"
        fi
        echo Selected branch ${BRANCH}
    - name: Pull Docker images
      run: |
        docker pull alexdegtyar/og-build:x86-latest
        docker pull alexdegtyar/og-test:x86-latest
    - name: Create artifacts directory
      run: mkdir ${{ env.ARTIFACTS_DIR }}
    - name: Build project
      run: |
        echo Build branch ${BRANCH}
        docker run \
        -e BRANCH="${BRANCH}" \
        -e ARTIFACTS="tests/tests" \
        -v ${{ env.ARTIFACTS_DIR }}:/var/og-artifacts \
        alexdegtyar/og-build:x86-latest
    - name: Run tests
      run: |
        docker run \
        -v ${{ env.ARTIFACTS_DIR }}:/var/og-artifacts \
        alexdegtyar/og-test:x86-latest
