name: Device Software
on:
  push:
    paths:
      - 'src/device/**'
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Pull Docker images
      run: |
        docker pull alexdegtyar/og-build:x86-latest
        docker pull alexdegtyar/og-test:x86-latest
    - name: Create artifacts directory
      run: mkdir ${{github.workspace}}/og-artifacts
    - name: Build project
      run: |
        echo "Branch: ${GITHUB_REF##*/}"
        docker run \
        -e BRANCH=${GITHUB_REF##*/} \
        -e ARTIFACTS="tests/tests" \
        -v ${{github.workspace}}/og-artifacts:/var/og-artifacts \
        alexdegtyar/og-build:x86-latest
    - name: List artifacts
      run: ls -al ${{github.workspace}}/og-artifacts
    - name: Run tests
      run: |
        docker run \
        -v ${{github.workspace}}/og-artifacts:/var/og-artifacts \
        alexdegtyar/og-test:x86-latest
