name: Web Application

on:
  push:
    paths:
      - 'src/webapp/**'
  pull_request:
    paths:
      - 'src/webapp/**'

defaults:
  run:
    working-directory: src/webapp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Dockerfile build for WebApp
      uses: docker/build-push-action@v2
      with:
        context: src/webapp
        file: src/webapp/Dockerfile.WebApp
        push: false # Just build here
